name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run
      run: |
        ./target/debug/mdopen -- README.md > mdopen.log 2>mdopen_error.log &
        sleep 3
    - name: Test
      run: HOST=127.0.0.1 PORT=5032 cargo test
